### PR TITLE
Do not raise an exception (and exit), if `fuser` is not found

### PR DESCRIPTION
**Pull request by wlang42**
Fix Issue #12

### CODE REVIEW

**Review by ale-rt — COMMENTED** [review]
Thanks for your contribution :)
LGTM, a changelog line would be desirable!

**Comment by wlang42** [comment]
> a changelog line would be desirable!
Yes! Unfortunatly i forgot to to add a commit message, and do not know, how to change it afterwards:-(
Should I create a new branch?

**Comment by ale-rt** [comment]
You can reuse the same branch:
- edit https://github.com/collective/collective.zopeedit/blob/master/docs/HISTORY.txt
- git commit -am "Added a changelog line"
- git push

Then I can take care of squashing the two commit.

**Comment by wlang42** [comment]
Done! Thank You for your support!

**Review by ale-rt — APPROVED** [review]

**Pull request closed without merging**
